### ISSUE TITLE
There seems to be a bug in the comparison of the Gridded/run_*/CHANOBS files: some of the files are not found.

### ISSUE THREAD

**Issue by jmccreight** [NCAR/wrf_hydro_nwm_public#64] opened 2018-05-31 21:23 UTC
https://travis-ci.com/NCAR/wrf_hydro_nwm/builds/74928143#L583

"None, None, None, None, None"
## Expected Behavior
It should find the files, they are there. Running tests/take_test.sh on this PR will reveal the issue.

## Current Behavior

It dosent find the files.

**Comment by jmills-ncar** [comment] 2018-05-31 22:01
I believe this is the cause:

This logic is responsible for the `None` print statements
https://github.com/NCAR/wrf_hydro_nwm_public/blob/master/tests/test_2_regression.py#L107-L114

```
    ```if all(v is None for v in chanobs_diffs):
        has_diffs = False
    else:
        has_diffs = True
        #chanobs_diffs.remove(None)
        for the_diff in chanobs_diffs[0:5]:
            with capsys.disabled():
                print(the_diff)```
```

I believe whats happening is that there is a diff but in a file that is not one of the first 5 in the list. We can resolve this by stripping all None values out of the list prior to the print statements

**Comment by jmills-ncar** [comment] 2018-05-31 22:05
This I believe would fix it, will submit a PR with it when I have a chance

[x for x in L if x is not None]

if all(v is None for v in chanobs_diffs):
        has_diffs = False
    else:
        has_diffs = True
        only_diffs = [the_diff for the_diff in chanobs_diffs if the_diff is not None]
        for the_diff in only_diffs[0:5]:
            with capsys.disabled():
                print(the_diff)

**Comment by jmills-ncar** [comment] 2018-08-15 16:45
This has been resolved as part of the testing refactor but I did not close with PR as I should have. Closing now

**Closed by jmills-ncar** 2018-08-15 16:45 UTC
Labels: Testing
