### ISSUE TITLE
Negative Evapotranspiration (ET)

### ISSUE THREAD

**Issue by youcanf** [NCAR/wrf_hydro_nwm_public#447] opened 2020-02-01 14:24 UTC
I have got negative accumulated evapotranspiration (ACCET) out of the LDASOUT_DOMAIN files. To show the problem in a simple way, I am attaching a slightly modified Croton case with no lake. A sample LDASOUT_DOMAIN file is included.
[test1.tar.gz](https://github.com/NCAR/wrf_hydro_nwm_public/files/4142637/test1.tar.gz)

## Expected Behavior

I would expect positive ET, unless negative ET here means something like dewfall.

## Current Behavior

Negative ACCET values in most areas of the domain contribute to mass balance error.

## Steps to Reproduce (for bugs)

1. Have a V5.1.1 compiled
2. Create a slurm job
3. Run the attached project
4. Check (ncview is enough) the ACCET from the LDASOUT_DOMAIN files since the second day

## Your Environment

* Version of the code used: 5.1.1.
* Operating System and version: Linux 3.1
* Compiler and version: ifort 18
* Other relevant information:

**Comment by kafitzgerald** [comment] 2020-02-05 22:20
Apologies for the slow response here.

Negative ET values can be produced by the model physics in Noah-MP and it looks like that is what you're showing here.  

For more details on the model physics in Noah-MP you might direct your question to [WRF-Hydro support](https://ral.ucar.edu/projects/wrf_hydro/contact).

I'm going to close this issue for now, but if it is confirmed to be a bug in the model physics we'll reopen this.

Thanks for reporting!

**Closed by kafitzgerald** 2020-02-05 22:20 UTC
