### ISSUE TITLE
WRF-Hydro V5.3 crashed with intel 2018 and netcdf4

### ISSUE THREAD

**Issue by andrewsoong** [NCAR/wrf_hydro_nwm_public#688] opened 2023-04-04 12:15 UTC
## Current Behavior

WRF-Hydro V5.3 crashed with intel 2018 and netcdf4. And the WRF-Hydro V5.2 is OK with the same intel and netcdf.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version of the code used:
* Operating System and version:
* Compiler and version:
* Other relevant information:
My HPC setup below::
[phd@mgmt NDHMS]$ ifort -v
ifort version 18.0.1

[phd@mgmt NDHMS]$ lsb_release -a LSB Version
LSB Version: :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description: CentOS release 6.9 (Final)
Release: 6.9
Codename: Final
[phd@mgmt NDHMS]$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)
cmake version 2.8.12.2

The errors is here: https://forum.mmm.ucar.edu/threads/the-wrf-hydro-v5-3-compiled-crash-with-intel-2018%EF%BC%8Cbut-the-wrf-hydro-v5-2-is-ok-with-the-same-intel-and-netcdf.12788/

**Comment by scrasmussen** [comment] 2023-04-04 19:42
@andrewsoong  Hi, on our system I've built and ran with Intel 18 with NetCDF 4.7.4 and Intel 19 with NetCDF 4.8.1. The output of those builds and tests all looked good to me. I wonder if there is an issue with the setup of your system or the step taken to compile? 

Can you try building with CMake, that is the simplest method and the least prone to go wrong. To do that first go to the top WRF-Hydro directory and enter:
```
$ mkdir build
$ cd build
$ cmake ..
$ make -j 4
```

The `wrf_hydro.exe` will be in the `build/Run` directory. If that step doesn't work can you please enter the error messages you're seeing and we'll try to figure out where the issue is. Thanks!

**Comment by andrewsoong** [comment] 2023-04-05 01:16
> @andrewsoong Hi, on our system I've built and ran with Intel 18 with NetCDF 4.7.4 and Intel 19 with NetCDF 4.8.1. The output of those builds and tests all looked good to me. I wonder if there is an issue with the setup of your system or the step taken to compile?
> 
> Can you try building with CMake, that is the simplest method and the least prone to go wrong. To do that first go to the top WRF-Hydro directory and enter:
> 
> ```
> $ mkdir build
> $ cd build
> $ cmake ..
> $ make -j 4
> ```
> 
> The `wrf_hydro.exe` will be in the `build/Run` directory. If that step doesn't work can you please enter the error messages you're seeing and we'll try to figure out where the issue is. Thanks!

Thank you so much ！ @scrasmussen 
The problem is Resolved with your method！
But before compiling， I need to modify line 10 of CMakeLists.txt to ：set (CMAKE_Fortran_COMPILER "mpiifort").
The compile was crashed without modification of  line 10 of CMakeLists.txt .

**Comment by andrewsoong** [comment] 2023-04-05 01:20
I will close this issue, because it was Resolved!
Thanks again!  @scrasmussen

**Closed** 2023-04-05 01:21 UTC
